version: "1"
services:
  - type: web
    name: businesspro-api
    env: node
    plan: free
    region: oregon
    rootDir: my-project/api
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-domain.vercel.app
